name: Build and Deploy

on:
  push:
    branches:
      - master # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name "Perry3939"
          git config --global user.email "parichita.personal@gmail.com"
          git add .
          git commit -m "Deploy to main branch"
          git push origin master
